[package]
name = "manualaid-cli"
version = "0.7.0"
edition = "2024"

[dependencies]
chrono.workspace = true
clap = { version = "4.6.5", features = ["derive"] }
crossterm = "0.29.0"
i18n.workspace = true
indexmap.workspace = true
manualaid-core.workspace = true
manualaid-ws.workspace = true
serde_json.workspace = true
similar.workspace = true
tokenx-rs = "0.1.0"
tokio.workspace = true
