//! # Description
//! Idempotent creation of ManualAid's standard directories and files.
//!
//! Missing targets are created with their default content; existing files
//! are never overwritten. The project `.ManualAid` directory is git-ignored,
//! so project-local files (such as `config.toml`) are never tracked.
//! # Test notes
//! The directory-creation error branch depends on OS state that tests
//! cannot construct portably (permission-denied paths); it is not required
//! to have high test coverage.
//! # 描述
//! ManualAid 标准目录与文件的幂等创建。
//!
//! 缺失的目标会被创建为默认内容；已存在的文件永不覆盖。项目的
//! `.ManualAid` 目录被 git 忽略，因此项目本地文件（如 `config.toml`）
//! 不会被跟踪。
//! # 测试说明
//! 目录创建的错误分支依赖测试无法跨平台构造的 OS 状态（权限拒绝路径）；
//! 该分支不要求高测试覆盖率。

use std::path::Path;

use crate::error::{CoreError, CoreResult};
use crate::file_io;
use crate::user_dir;

/// A file that [`ensure_manualaid_dirs`] creates when missing. Its parent
/// directory is `<base>/.ManualAid`, where `base` is the user home or the
/// project root.
/// 缺失时由 [`ensure_manualaid_dirs`] 创建的文件。其父目录为
/// `<base>/.ManualAid`，`base` 为用户主目录或项目根。
struct FileTarget {
    /// `true`: create under the user home; `false`: under the project root.
    /// `true`：创建于用户主目录下；`false`：创建于项目根下。
    home: bool,
    /// File name within `.ManualAid`.
    /// `.ManualAid` 内的文件名。
    name: &'static str,
    /// Exact content written for a new file (config files carry a minimal
    /// valid TOML document).
    /// 新建文件写入的确切内容（配置文件为最小的合法 TOML 文档）。
    content: &'static str,
}

/// Content of the generated home `.ManualAid/config.toml`; a valid empty
/// TOML document.
/// 生成的 `~/.ManualAid/config.toml` 的内容；一个合法的空 TOML 文档。
pub const DEFAULT_GLOBAL_CONFIG_CONTENT: &str = "\n";

/// Content of the generated project `.ManualAid/config.toml`; the `[skill]`
/// table used by [`crate::skill`] for enable/disable state.
/// 生成的项目 `.ManualAid/config.toml` 的内容；[`crate::skill`] 用于
/// 启用/禁用状态的 `[skill]` 表。
pub const DEFAULT_PROJECT_CONFIG_CONTENT: &str = "[skill]\n";

/// Content of the generated project `.ManualAid/.gitignore`; ignores every
/// file in the directory so the project config stays untracked.
/// 生成的项目 `.ManualAid/.gitignore` 的内容；忽略目录内所有文件，使项目
/// 配置不被跟踪。
pub const GITIGNORE_CONTENT: &str = "# Automatically generated by ManualAid\n*\n";

/// Ordered list of (directory, file-with-content) targets; one line per
/// future default file.
/// （目录、含内容的文件）目标的有序列表；未来每新增一个默认文件只需一行。
const FILE_TARGETS: &[FileTarget] = &[
    FileTarget {
        home: true,
        name: "config.toml",
        content: DEFAULT_GLOBAL_CONFIG_CONTENT,
    },
    FileTarget {
        home: false,
        name: "config.toml",
        content: DEFAULT_PROJECT_CONFIG_CONTENT,
    },
    FileTarget {
        home: false,
        name: ".gitignore",
        content: GITIGNORE_CONTENT,
    },
];

/// # Description
/// Idempotently create ManualAid's standard directories and files: the
/// missing targets listed in the module documentation are created with their
/// default content. Existing files are never overwritten.
/// # 描述
/// 幂等地创建 ManualAid 的标准目录与文件：缺失时按模块文档列出的目标
/// 创建默认内容；已存在的文件永不覆盖。
pub fn ensure_manualaid_dirs(project_root: &Path) -> CoreResult<()> {
    let home = user_dir::home_dir()?;
    ensure_manualaid_dirs_impl(project_root, &home)
}

/// # Description
/// Like [`ensure_manualaid_dirs`] with an explicit home directory, used by
/// tests to avoid touching the real user home. Hidden from docs.
/// # 描述
/// 同 [`ensure_manualaid_dirs`]，但以显式指定的主目录代替真实用户主目录，
/// 供测试避免触碰真实主目录。文档中隐藏。
#[doc(hidden)]
pub fn ensure_manualaid_dirs_with_home(project_root: &Path, home: &Path) -> CoreResult<()> {
    ensure_manualaid_dirs_impl(project_root, home)
}

fn ensure_manualaid_dirs_impl(project_root: &Path, home: &Path) -> CoreResult<()> {
    let root = std::path::absolute(project_root).map_err(CoreError::from)?;

    for target in FILE_TARGETS {
        let base = if target.home { home } else { &root };
        let dir = base.join(".ManualAid");
        std::fs::create_dir_all(&dir).map_err(|e| {
            CoreError::Io(format!("cannot create directory `{}`: {e}", dir.display()))
        })?;

        let file = dir.join(target.name);
        file_io::with_file_lock(&file, || {
            if !file.exists() {
                std::fs::write(&file, target.content).map_err(CoreError::from)?;
            }
            Ok(())
        })?;
    }
    Ok(())
}
